#include "neat.v1\native\players\players.methods.pwn"
#include "neat.v1\native\positions\positions.methods.pwn"
#include "neat.v1\native\areas\areas.methods.pwn"
#include "neat.v1\native\vehicles\vehicles.methods.pwn"
// #include "neat.v1\native\objects\objects.methods.pwn"
#include "neat.v1\native\windows\windows.methods.pwn"
#include "neat.v1\native\textdraws\textdraws.methods.pwn"
#include "neat.v1\native\keys\keys.methods.pwn"
#include "neat.v1\native\commands\commands.methods.pwn"
#include "neat.v1\native\pickups\pickups.methods.pwn"
#include "neat.v1\native\worlds\worlds.methods.pwn"
#include "neat.v1\native\chat\chat.methods.pwn"
#include "neat.v1\native\timers\timers.methods.pwn"