#include "neat.v1\native\positions\positions.handlers.pwn"
#include "neat.v1\native\areas\areas.handlers.pwn"
#include "neat.v1\native\vehicles\vehicles.handlers.pwn"
// #include "neat.v1\native\objects\objects.handlers.pwn"
#include "neat.v1\native\players\players.handlers.pwn"
#include "neat.v1\native\windows\windows.handlers.pwn"
#include "neat.v1\native\textdraws\textdraws.handlers.pwn"
#include "neat.v1\native\keys\keys.handlers.pwn"
#include "neat.v1\native\commands\commands.handlers.pwn"
#include "neat.v1\native\pickups\pickups.handlers.pwn"
#include "neat.v1\native\worlds\worlds.handlers.pwn"
#include "neat.v1\native\chat\chat.handlers.pwn"