#include "neat.v1\native\positions\positions.properties.pwn"
#include "neat.v1\native\players\players.properties.pwn"
#include "neat.v1\native\vehicles\vehicles.properties.pwn"
#include "neat.v1\native\areas\areas.properties.pwn"
// #include "neat.v1\native\objects\objects.properties.pwn"
#include "neat.v1\native\windows\windows.properties.pwn"
#include "neat.v1\native\keys\keys.properties.pwn"
#include "neat.v1\native\textdraws\textdraws.properties.pwn"
#include "neat.v1\native\commands\commands.properties.pwn"
#include "neat.v1\native\pickups\pickups.properties.pwn"
#include "neat.v1\native\worlds\worlds.properties.pwn"
#include "neat.v1\native\chat\chat.properties.pwn"
#include "neat.v1\native\timers\timers.properties.pwn"