#include "neat.v1\native\players\players.macro.pwn"
#include "neat.v1\native\positions\positions.macro.pwn"
#include "neat.v1\native\areas\areas.macro.pwn"
#include "neat.v1\native\vehicles\vehicles.macro.pwn"
// #include "neat.v1\native\objects\objects.macro.pwn"
#include "neat.v1\native\windows\windows.macro.pwn"
#include "neat.v1\native\textdraws\textdraws.macro.pwn"
#include "neat.v1\native\keys\keys.macro.pwn"
#include "neat.v1\native\commands\commands.macro.pwn"
#include "neat.v1\native\pickups\pickups.macro.pwn"
#include "neat.v1\native\worlds\worlds.macro.pwn"
#include "neat.v1\native\chat\chat.macro.pwn"
#include "neat.v1\native\timers\timers.macro.pwn"